version: '3'

services:

  prometheus:
    image: prom/prometheus:latest
    command:
      - --config.file=/etc/prometheus/prometheus.yaml
    ports:
      - "9090"
    volumes:
      - ./prometheus.yaml:/etc/prometheus/prometheus.yaml
    networks:
      - prometheus

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000"
    volumes:
      - ./grafana-provisioning/dashboards:/etc/grafana/provisioning/dashboards
      - ./grafana-provisioning/datasources:/etc/grafana/provisioning/datasources
    networks:
      - prometheus

  node_exporter:
    image: prom/node-exporter:latest
    ports:
      - "9100"
    networks:
      - prometheus

  flask-app:
    image: 704505749045.dkr.ecr.us-east-1.amazonaws.com/liorm-nanox:monitor-app
    ports:
      - "80:80"
    volumes:
      - /home/ubuntu/systemlogs:/host_logs
    networks:
      - frontend
      - prometheus

networks:
  prometheus:
  frontend:
  
