{
 "title": "Node Monitoring",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12 },
   "targets": [
    {
     "expr": "(sum by (cpu)(rate(node_cpu_seconds_total{mode!='idle'}[5m]))*100)",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12 },
   "targets": [
    {
     "expr": "node_memory_Active_bytes/node_memory_MemTotal_bytes*100",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Disk Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12 },
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{fstype!~'tmpfs|squashfs'} - node_filesystem_free_bytes{fstype!~'tmpfs|squashfs'}",
     "legendFormat": "{{ instance }}"
    }
   ]
  }
 ]
}